federation_version: =2.7.0
subgraphs:
  products:
    routing_url: http://localhost:4001/products/graphql
    schema:
      file: ../subgraphs/products/schema.graphql
  reviews:
    routing_url: http://localhost:4001/reviews/graphql
    schema:
      file: ../subgraphs/reviews/schema.graphql
  users:
    routing_url: http://localhost:4001/users/graphql
    schema:
      file: ../subgraphs/users/schema.graphql
